splash screen at 88
cimplesid/Flutter-for-beginners pull request #11
Opened 2020-10-29 06:17 UTC by denpufa

create a splash screen tutorial to any app with flutter using the dart async .

2020-10-29 06:51 UTC, cimplesid requested changes

2020-10-29 06:51 UTC, cimplesid commented on 88-splash-screen/main.dart
> +      Navigator.pushNamed(context, '/nextRoute');
make a next route widget too

2020-11-01 01:41 UTC, denpufa reviewed
add a new route widget

2020-11-01 02:20 UTC, cimplesid approved these changes

2020-11-01 02:20 UTC, merged